version: "3.3"
services:

    server-java:
        container_name: odatajavaservice
        image: tomcat:jdk8-adoptopenjdk-openj9
        volumes:
            - ./webapps:/usr/local/tomcat/webapps/
            - ./scripts:/scripts
        networks:
            - programas_default
        ports:
            - "8080:8080"
        command: bash /scripts/conectionTester.sh
networks:
    programas_default:
        external: true
